#define		SET_BIT(VAR, BIT_NO)			(VAR |= (1<<BIT_NO) ) 
#define		CLEAR_BIT(VAR, BIT_NO)			(VAR &= ~(1<<BIT_NO) ) 
#define		TOGGEL_BIT(VAR, BIT_NO)			(VAR ^= (1<<BIT_NO) ) 
#define		GET_BIT(VAR, BIT_NO)			((VAR & (1<<BIT_NO))>>BIT_NO) 
#define		CHECK_BIT(VAR,BIT_NO)			((VAR>>BIT_NO)&1)
#define 	ASSIGN_BIT(VAR,BIT_NO,VAL)		(VAR= (VAR& ~(1<<BIT_NO)) | (VAL<<BIT_NO))